Repository Asilo5/tantive-star-wars, pull requests merged in 2019-12, with the labels that each got.

#1 Setup files
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/App/App.scss
  src/Components/App/App.test.js
  src/Components/CharacterCard/CharacterCard.js
  src/Components/CharacterCard/CharacterCard.scss
  src/Components/CharacterCard/CharacterCard.test.js
  src/Components/CharactersContainer/CharactersContainer.js
  src/Components/CharactersContainer/CharactersContainer.scss
  src/Components/CharactersContainer/CharactersContainer.test.js
  src/Components/FavouritesContainer/FavouritesContainer.js
  src/Components/FavouritesContainer/FavouritesContainer.scss
  src/Components/FavouritesContainer/FavouritesContainer.test.js
  src/Components/Login/Login.js
  src/Components/Login/Login.scss
  src/Components/Login/Login.test.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MovieCard/MovieCard.scss
  src/Components/MovieCard/MovieCard.test.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/Components/MoviesContainer/MoviesContainer.scss
  src/Components/MoviesContainer/MoviesContainer.test.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
  src/Components/NavBar/NavBar.test.js
  src/Components/ScrollText/ScrollText.js
  src/Components/ScrollText/ScrollText.scss
  src/Components/ScrollText/ScrollText.test.js
Labels: files added

#22 Start router
  package-lock.json
  package.json
  src/Components/App/App.js
  src/index.js
Labels: enhancement

#24 Start login
  src/Components/Login/Login.js
Labels: Iteration 1 - Landing Page, enhancement

#26 Continue form
  src/Components/App/App.js
  src/Components/Login/Login.js
  src/Components/Login/Login.scss
Labels: Added Style, Iteration 1 - Landing Page

#27 Error handling login
  src/Components/Login/Login.js
  src/Components/Login/Login.scss
Labels: Added Style, enhancement

#31 Add rank message
  src/Components/Login/Login.js
  src/Components/Login/Login.scss
Labels: Added Style, enhancement

#33 Aw test fetch
  src/Components/App/App.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/apiCalls.js
Labels: Iteration 2 - The Movies

#34 Test login
  package-lock.json
  package.json
  src/Components/Login/Login.js
  src/Components/Login/Login.test.js
  src/Components/Login/__snapshots__/Login.test.js.snap
  src/setupTests.js
Labels: Add Tests, Iteration 1 - Landing Page

#41 Add conditional rendering for isLoading for MoviesContainer
  src/Components/App/App.js
Labels: bug, enhancement

#42 Add style loading img
  src/Components/App/App.js
  src/Components/App/App.scss
Labels: enhancement

#40 Character fetch
  src/Components/App/App.js
  src/apiCalls.js
Labels: Added fetches, enhancement

#45 Start navbar
  src/Components/App/App.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/Components/MoviesContainer/MoviesContainer.scss
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
  src/Components/NavBar/NavBar.test.js
  src/Components/NavBar/__snapshots__/NavBar.test.js.snap
Labels: Add Tests, Added Style, enhancement

#50 Fix characters api
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/apiCalls.js
Labels: bug, enhancement

#54 Start character comp
  src/Components/CharacterCard/CharacterCard.js
  src/Components/CharacterCard/CharacterCard.test.js
  src/Components/CharacterCard/__snapshots__/CharacterCard.test.js.snap
  src/Components/CharactersContainer/CharactersContainer.js
  src/Components/CharactersContainer/CharactersContainer.test.js
  src/Components/CharactersContainer/__snapshots__/CharactersContainer.test.js.snap
Labels: Add Tests, enhancement

#57 Style characters
  package-lock.json
  package.json
  src/Components/CharacterCard/CharacterCard.js
  src/Components/CharacterCard/CharacterCard.scss
  src/Components/CharacterCard/__snapshots__/CharacterCard.test.js.snap
  src/Components/CharactersContainer/CharactersContainer.js
  src/Components/CharactersContainer/CharactersContainer.scss
  src/Components/CharactersContainer/__snapshots__/CharactersContainer.test.js.snap
  src/Components/Login/__snapshots__/Login.test.js.snap
Labels: Add Tests, Added Style, Iteration 3 - The Characters, enhancement, files added

#59 Aw api test
  src/apiCalls.js
  src/apiCalls.test.js
Labels: Add Tests

#60 Start favouriting
  src/Components/App/App.js
  src/Components/CharacterCard/CharacterCard.js
  src/Components/CharacterCard/CharacterCard.scss
  src/Components/CharactersContainer/CharactersContainer.js
Labels: Added Style, Iteration 4 - User’s Favorites, enhancement

#62 Fix navbar
  src/Components/App/App.js
  src/Components/CharactersContainer/CharactersContainer.js
  src/Components/CharactersContainer/CharactersContainer.scss
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
Labels: Added Style, Fixed Bug, Iteration 4 - User’s Favorites, enhancement

#67 Fix scrolls
  src/Components/App/App.js
  src/Components/CharactersContainer/CharactersContainer.scss
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/Components/ScrollText/ScrollText.js
  src/Components/ScrollText/ScrollText.scss
  src/Components/ScrollText/ScrollText.test.js
  src/Components/ScrollText/__snapshots__/ScrollText.test.js.snap
Labels: Add Tests, Added Style, enhancement

#68 Reset state on logout
  src/Components/App/App.js
  src/Components/NavBar/NavBar.js
Labels: enhancement

#70 Fix layout favourites
  src/Components/FavouritesContainer/FavouritesContainer.scss
Labels: Added Style

#71 Style nav button
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
Labels: Added Style

#72 Remove height from go back to movies button in Favourites container
  src/Components/FavouritesContainer/FavouritesContainer.scss
Labels: Added Style

#73 Add proptypes
  package.json
  src/Components/App/App.js
  src/Components/CharacterCard/CharacterCard.js
  src/Components/CharactersContainer/CharactersContainer.js
  src/Components/FavouritesContainer/FavouritesContainer.js
  src/Components/Login/Login.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/Components/NavBar/NavBar.js
  src/Components/ScrollText/ScrollText.js
Labels: enhancement

#75 Add linter
  .eslintrc.json
  package-lock.json
  package.json
Labels: files added

#79 Update login failing test to pass
  src/Components/Login/Login.js
  src/Components/Login/Login.test.js
Labels: Add Tests
